version: '2.2'

services:
  postgres:
    container_name: postgres_db
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped
    networks:
      - postgres_db

  school-api:
    container_name: school-api
    image: evvgen/school-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/diary
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8088:8080"
    networks:
      - postgres_db
    depends_on:
      - postgres
    restart: unless-stopped

  school-react:
    container_name: school-react
    image: evvgen/school-react
    build:
      context: frontend
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - school-api
    restart: unless-stopped

volumes:
  postgres:

networks:
  postgres_db: