server:
  error:
    include-message: always


logging:
  level:
    com.evggenn.school.teacher: INFO

cors:
#  allowed-origins: "http://localhost:5173"
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 5MB

  application:
    name: school

  datasource:
    url: jdbc:postgresql://localhost:5332/diary
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

    show-sql: true

    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true






