server:
  error:
    include-message: always


cors:
  allowed-origins: "*"
  allowed-methods: "*"

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 5MB

  application:
    name: school

  datasource:
    url: jdbc:postgresql://localhost:5432/diary
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#  sql:
#    init:
#      mode: always





