name: CD - Deploy React Frontend

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#    paths:
#      - frontend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Docker Build and push
        run: |
          chmod +x ../../.ci/build-publish.sh
          USERNAME=evvgen \
          REPO=school-react \
          TAG=${{ steps.build-number.outputs.BUILD_NUMBER }} \
          ../.cicd/build-publish.sh . \
          --build-arg api_base_url=https://school-api-mt8g.onrender.com:8080
